version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install cfn-lint boto3 awscli

  pre_build:
    commands:
      - echo "Running CloudFormation Linter..."
      - cfn-lint templates/*.yaml || true
      - echo "Linting complete."

  build:
    commands:
      - echo "Validating CloudFormation templates..."
      - for template in templates/*.yaml; do
          if [ -f "$template" ]; then
            echo "Validating $template";
            aws cloudformation validate-template --template-body file://$template || exit 1;
          fi;
        done
      - echo "All templates validated successfully."

  post_build:
    commands:
      - echo "Preparing artifacts for deployment..."
      - mkdir -p output
      - cp -r templates/*.yaml output/
      - echo "Build completed successfully."

artifacts:
  files:
    - '*.yaml'
  base-directory: output
  discard-paths: yes
