AWSTemplateFormatVersion: '2010-09-09'
Description: Multi-region CI/CD Pipeline for 3-tier CloudFormation app

Parameters:
  GitHubOwner:
    Type: String
    Default: anzy-anzy

  GitHubRepo:
    Type: String
    Default: cicd-3tier-cloudformation

  GitHubBranch:
    Type: String
    Default: main

  GitHubToken:
    Type: String
    NoEcho: true

  ProjectName:
    Type: String
    Default: cicd-pipeline-stack

  ArtifactBucketEastName:
    Type: String
    Default: ""

  ArtifactBucketWestName:
    Type: String
    Default: ""

Conditions:
  CreateEastBucket: !Equals [!Ref ArtifactBucketEastName, ""]
  CreateWestBucket: !Equals [!Ref ArtifactBucketWestName, ""]

Resources:

  ArtifactBucketEast:
    Type: AWS::S3::Bucket
    Condition: CreateEastBucket
    DeletionPolicy: Retain

  ArtifactBucketWest:
    Type: AWS::S3::Bucket
    Condition: CreateWestBucket
    DeletionPolicy: Retain

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - cloudformation:*
                  - iam:PassRole
                Resource: "*"

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:*
                  - cloudformation:ValidateTemplate
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-build"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ProjectName}-multi-region-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn

      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !If
              - CreateEastBucket
              - !Ref ArtifactBucketEast
              - !Ref ArtifactBucketEastName

        - Region: us-west-2
          ArtifactStore:
            Type: S3
            Location: !If
              - CreateWestBucket
              - !Ref ArtifactBucketWest
              - !Ref ArtifactBucketWestName

      Stages:

        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - SourceArtifact
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - SourceArtifact
              OutputArtifacts:
                - BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProject

        ####################################################
        # DEPLOY DEV — APP FIRST (correct order)
        ####################################################
        - Name: DeployDev
          Actions:

            - Name: DeployAppDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - BuildArtifact
              Region: us-east-1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CodePipelineRole.Arn
                StackName: app-stack-dev
                TemplatePath: BuildArtifact::templates/app.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: !Sub |
                  {
                    "EnvName": "DEV",
                    "ArtifactBucket": "${ArtifactBucketEastName}"
                  }
              RunOrder: 1

            - Name: DeployDBDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - BuildArtifact
              Region: us-east-1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CodePipelineRole.Arn
                StackName: db-stack-dev
                TemplatePath: BuildArtifact::templates/db.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: '{"EnvName": "DEV"}'
              RunOrder: 2

        - Name: ManualApproval
          Actions:
            - Name: ApproveForProd
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1

        ####################################################
        # DEPLOY PROD — APP FIRST
        ####################################################
        - Name: DeployProd
          Actions:

            - Name: DeployAppProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - BuildArtifact
              Region: us-west-2
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CodePipelineRole.Arn
                StackName: app-stack-prod
                TemplatePath: BuildArtifact::templates/app.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: !Sub |
                  {
                    "EnvName": "PROD",
                    "ArtifactBucket": "${ArtifactBucketWestName}"
                  }
              RunOrder: 1

            - Name: DeployDBProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - BuildArtifact
              Region: us-west-2
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CodePipelineRole.Arn
                StackName: db-stack-prod
                TemplatePath: BuildArtifact::templates/db.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: '{"EnvName":"PROD"}'
              RunOrder: 2

Outputs:
  PipelineName:
    Value: !Ref CICDPipeline
