AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Multi-region CI/CD Pipeline for 3-tier CloudFormation app
  (Dev in us-east-1, Prod in us-west-2)

Parameters:
  GitHubOwner:
    Type: String
    Default: anzy-anzy
  GitHubRepo:
    Type: String
    Default: cicd-3tier-cloudformation
  GitHubBranch:
    Type: String
    Default: main
  GitHubToken:
    Type: String
    NoEcho: true
  ProjectName:
    Type: String
    Default: cicd-pipeline-stack

  # New: optional, pass existing artifact bucket names to reuse
  ArtifactBucketEastName:
    Type: String
    Default: ""
    Description: "(optional) Existing S3 bucket name in us-east-1 for CodePipeline artifacts"
  ArtifactBucketWestName:
    Type: String
    Default: ""
    Description: "(optional) Existing S3 bucket name in us-west-2 for CodePipeline artifacts"

Conditions:
  CreateEastBucket: !Equals [!Ref ArtifactBucketEastName, ""]
  CreateWestBucket: !Equals [!Ref ArtifactBucketWestName, ""]

Resources:
  #############################################
  # S3 Buckets for Artifacts (only if needed)
  #############################################
  ArtifactBucketEast:
    Type: AWS::S3::Bucket
    Condition: CreateEastBucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: {}  # let CFN pick a unique name

  ArtifactBucketWest:
    Type: AWS::S3::Bucket
    Condition: CreateWestBucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: {}  # let CFN pick a unique name

  #############################################
  # IAM Role for CodePipeline
  #############################################
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-CodePipelineRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - cloudformation:*
                  - cloudformation:DescribeStacks
                  - iam:PassRole
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                  - rds:DescribeDBInstances
                  - rds:DescribeDBSubnetGroups
                  - ec2:DescribeKeyPairs
                  - ec2:DescribeSecurityGroups
                Resource: "*"

  #############################################
  # IAM Role for CodeBuild
  #############################################
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:*
                  - cloudformation:ValidateTemplate
                  - secretsmanager:GetSecretValue
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: "*"

  #############################################
  # CodeBuild Project
  #############################################
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-build"
      Description: "Validate and package CloudFormation templates"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 15

  #############################################
  # CodePipeline Definition
  #############################################
  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ProjectName}-multi-region-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !If
              - CreateEastBucket
              - !Ref ArtifactBucketEast
              - !Ref ArtifactBucketEastName
        - Region: us-west-2
          ArtifactStore:
            Type: S3
            Location: !If
              - CreateWestBucket
              - !Ref ArtifactBucketWest
              - !Ref ArtifactBucketWestName
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProject

        - Name: DeployDev
          Actions:
            - Name: DeployDBDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-east-1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: dev-db-stack
                TemplatePath: BuildArtifact::templates/db.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                ParameterOverrides: '{"EnvName":"DEV"}'

            - Name: DeployAppDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-east-1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: dev-app-stack
                TemplatePath: BuildArtifact::templates/app.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                ParameterOverrides: '{"EnvName":"DEV"}'

        - Name: ManualApproval
          Actions:
            - Name: ApproveForProd
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1

        - Name: DeployProd
          Actions:
            - Name: DeployDBProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-west-2
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: prod-db-stack
                TemplatePath: BuildArtifact::templates/db.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                ParameterOverrides: '{"EnvName":"PROD"}'

            - Name: DeployAppProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-west-2
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: prod-app-stack
                TemplatePath: BuildArtifact::templates/app.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                ParameterOverrides: '{"EnvName":"PROD"}'

Outputs:
  PipelineName:
    Description: Name of the pipeline
    Value: !Ref CICDPipeline
