AWSTemplateFormatVersion: '2010-09-09'
Description: Multi-region CI/CD Pipeline for 3-tier project

Parameters:
  GitHubToken:
    Type: String
    NoEcho: true
  GitHubRepo:
    Type: String
    Default: cicd-3tier-cloudformation
  GitHubOwner:
    Type: String
    Default: anzy-anz
  GitHubBranch:
    Type: String
    Default: main

Resources:

  ################################
  # IAM ROLE FOR CODEPIPELINE
  ################################
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetBucketLocation
                Resource: "*"         #  change to a specific resource to enforce least privilege principle
                
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"

  ################################
  # IAM ROLE FOR CODEBUILD
  ################################
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:*        #Limit to only needed actions GetObject because CodeBuild doesn't write to your bucket
                  - cloudformation:*    #Again limit to the needed actions 
                Resource: "*"     #Limit to the needed resources.

  ################################
  # CODEBUILD PROJECT
  ################################
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: CICD-BuildProject
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER

  ##############################################
  # MULTI-REGION ARTIFACT STORES (mandatory)
  ##############################################
  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: cicd-pipeline-stack-multi-region-pipeline
      RoleArn: !GetAtt CodePipelineRole.Arn

      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: 436083576844-cicd-pipeline-stack-us-east-1-artifacts

        - Region: us-west-2
          ArtifactStore:
            Type: S3
            Location: 436083576844-cicd-pipeline-stack-us-west-2-artifacts-v2

      Stages:

        ###########################################
        # SOURCE STAGE
        ###########################################
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              RunOrder: 1

        ###########################################
        # BUILD STAGE
        ###########################################
        - Name: Build
          Actions:
            - Name: CodeBuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1

        ###########################################
        # DEPLOY TO us-east-1 (DEV)
        ###########################################
        - Name: Deploy-Dev-us-east-1
          Actions:
            - Name: CloudFormationDeployDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: app-stack-dev
                Capabilities: CAPABILITY_IAM
                Region: us-east-1
                TemplatePath: BuildArtifact::templates/app.yaml
                ParameterOverrides: |
                  {
                    "EnvName": "DEV",
                    "ArtifactBucket": "436083576844-cicd-pipeline-stack-us-east-1-artifacts"
                  }
              RunOrder: 1

        ###########################################
        # DEPLOY TO us-west-2 (PROD)
        ###########################################
        - Name: Deploy-Prod-us-west-2
          Actions:
            - Name: CloudFormationDeployProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: app-stack-prod
                Capabilities: CAPABILITY_IAM
                Region: us-west-2
                TemplatePath: BuildArtifact::templates/app.yaml
                ParameterOverrides: |
                  {
                    "EnvName": "PROD",
                    "ArtifactBucket": "436083576844-cicd-pipeline-stack-us-west-2-artifacts-v2"
                  }
              RunOrder: 1

Outputs:
  PipelineName:
    Value: !Ref CICDPipeline
