#####################################
# Deploy VPC Stack
#####################################
- Name: DeployVPC
  Actions:
    - Name: DeployVPCStack
      ActionTypeId:
        Category: Deploy
        Owner: AWS
        Provider: CloudFormation
        Version: 1
      InputArtifacts:
        - Name: BuildArtifact
      Configuration:
        ActionMode: CREATE_UPDATE
        StackName: !Sub "${ProjectName}-vpc"
        TemplatePath: BuildArtifact::output/vpc.yaml
        Capabilities: CAPABILITY_IAM
        ParameterOverrides: |
          {
            "EnvName": "DEV"
          }

#####################################
# Deploy DB Stack (depends on VPC)
#####################################
- Name: DeployDB
  Actions:
    - Name: DeployDBStack
      ActionTypeId:
        Category: Deploy
        Owner: AWS
        Provider: CloudFormation
        Version: 1
      InputArtifacts:
        - Name: BuildArtifact
      Configuration:
        ActionMode: CREATE_UPDATE
        StackName: !Sub "${ProjectName}-db"
        TemplatePath: BuildArtifact::output/db.yaml
        Capabilities: CAPABILITY_IAM
        ParameterOverrides: |
          {
            "EnvName": "DEV"
          }

#####################################
# Deploy APP Stack
#####################################
- Name: DeployApp
  Actions:
    - Name: DeployAppStack
      ActionTypeId:
        Category: Deploy
        Owner: AWS
        Provider: CloudFormation
        Version: 1
      InputArtifacts:
        - Name: BuildArtifact
      Configuration:
        ActionMode: CREATE_UPDATE
        StackName: !Sub "${ProjectName}-app"
        TemplatePath: BuildArtifact::output/app.yaml
        Capabilities: CAPABILITY_IAM
        ParameterOverrides: |
          {
            "EnvName": "DEV"
          }
