AWSTemplateFormatVersion: '2010-09-09'
Description: Multi-region CI/CD Pipeline for 3-tier CloudFormation app

Parameters:
  GitHubOwner:
    Type: String
    Default: anzy-anzy

  GitHubRepo:
    Type: String
    Default: cicd-3tier-cloudformation

  GitHubBranch:
    Type: String
    Default: main

  GitHubToken:
    Type: String
    NoEcho: true

Resources:

  ###################################################
  # IAM Roles
  ###################################################
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - cloudformation:*
                  - iam:PassRole
                Resource: "*"

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:*
                  - cloudformation:ValidateTemplate
                Resource: "*"

  ###################################################
  # CodeBuild
  ###################################################
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: cicd-3tier-build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  ###################################################
  # CodePipeline
  ###################################################
  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: cicd-pipeline-stack-multi-region-pipeline
      RoleArn: !GetAtt CodePipelineRole.Arn

      ArtifactStore:
        Type: S3
        Location: 436083576844-cicd-pipeline-stack-us-east-1-artifacts

      Stages:

        ###################################################
        # SOURCE STAGE
        ###################################################
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken

        ###################################################
        # BUILD STAGE
        ###################################################
        - Name: Build
          Actions:
            - Name: CodeBuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProject

        ###################################################
        # DEPLOY DEV
        ###################################################
        - Name: DeployDev
          Actions:
            - Name: DeployAppDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-east-1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: app-stack-dev
                TemplatePath: BuildArtifact::templates/app.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: |
                  {
                    "EnvName": "DEV",
                    "ArtifactBucket": "436083576844-cicd-pipeline-stack-us-east-1-artifacts"
                  }
              RunOrder: 1

            - Name: DeployDBDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-east-1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: db-stack-dev
                TemplatePath: BuildArtifact::templates/db.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: |
                  { "EnvName": "DEV" }
              RunOrder: 2

        ###################################################
        # MANUAL APPROVAL
        ###################################################
        - Name: ManualApproval
          Actions:
            - Name: ApproveForProd
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1

        ###################################################
        # DEPLOY PROD
        ###################################################
        - Name: DeployProd
          Actions:
            - Name: DeployAppProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-west-2
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: app-stack-prod
                TemplatePath: BuildArtifact::templates/app.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: |
                  {
                    "EnvName": "PROD",
                    "ArtifactBucket": "436083576844-cicd-pipeline-stack-us-west-2-artifacts-v2"
                  }
              RunOrder: 1

            - Name: DeployDBProd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-west-2
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: db-stack-prod
                TemplatePath: BuildArtifact::templates/db.yaml
                Capabilities: CAPABILITY_IAM
                ParameterOverrides: |
                  { "EnvName": "PROD" }
              RunOrder: 2

Outputs:
  PipelineName:
    Value: !Ref CICDPipeline
