AWSTemplateFormatVersion: '2010-09-09'
Description: App EC2 instance inside VPC, connected to RDS (3-tier CI/CD project)

Parameters:
  EnvName:
    Type: String
    AllowedValues:
      - DEV
      - PROD

  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64"

Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and DB access
      VpcId: !ImportValue
        'Fn::Sub': '${EnvName}-VpcId'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.20.0.0/16
      Tags:
        - Key: Name
          Value: !Sub '${EnvName}-app-sg'

  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t3.micro
      SubnetId: !Select
        - 0
        - !Split
          - ","
          - !ImportValue
            !Sub "${EnvName}-PubSubnets"
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      KeyName: mykeypair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install -y nginx1
          systemctl enable nginx
          systemctl start nginx
          echo "<h1>${EnvName} Web App connected to DB: $(aws secretsmanager get-secret-value --secret-id myapp/dbcredentials --query SecretString --output text)</h1>" > /usr/share/nginx/html/index.html
      Tags:
        - Key: Name
          Value: !Sub '${EnvName}-app-instance'

Outputs:
  AppInstanceId:
    Description: EC2 instance ID
    Value: !Ref AppInstance

  AppPublicIP:
    Description: Public IP of the app instance
    Value: !GetAtt AppInstance.PublicIp
