AWSTemplateFormatVersion: '2010-09-09'
Description: >
  EC2 Application Stack for 3-tier CI/CD Project.
  Deploys EC2 instance, installs Apache, pulls website files from S3.

Parameters:
  EnvName:
    Type: String
    Default: DEV

  InstanceType:
    Type: String
    Default: t3.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: mykeypair

  AmiId:
    Type: String
    Default: ""

  ArtifactBucket:
    Type: String
    Description: "S3 bucket where CodePipeline stores build artifacts"

  ForceUpdate:
    Type: String
    Default: "1"

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-06dd5c911c0d8dcdc
    us-west-2:
      AMI: ami-04f9aa2b7c7091927

Conditions:
  UseProvidedAmi: !Not [!Equals [!Ref AmiId, ""]]

Resources:

  ###################################
  # Security Group
  ###################################
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH traffic
      VpcId: !ImportValue
        Fn::Sub: "${EnvName}-VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ###################################
  # EC2 Instance
  ###################################
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !If
        - UseProvidedAmi
        - !Ref AmiId
        - !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      KeyName: !Ref KeyName

      SubnetId: !Select
        - 0
        - !Split
          - ","
          - !ImportValue
              Fn::Sub: "${EnvName}-PublicSubnets"

      SecurityGroupIds:
        - !Ref AppSecurityGroup

      ############################################
      # USER DATA — INSTALL APACHE & COPY WEBSITE
      ############################################
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd awscli

          systemctl start httpd
          systemctl enable httpd

          mkdir -p /opt/app

          # Download website file from the CodePipeline artifact structure
          aws s3 cp s3://${ArtifactBucket}/app/index.html /opt/app/index.html

          cp /opt/app/index.html /var/www/html/index.html
          chmod 644 /var/www/html/index.html

          echo "Website deployed successfully"

      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-AppServer"
        - Key: ForceUpdate
          Value: !Ref ForceUpdate

Outputs:
  AppInstanceId:
    Value: !Ref AppInstance
    Export:
      Name: !Sub "${EnvName}-AppInstanceId"

  AppSecurityGroupId:
    Value: !Ref AppSecurityGroup
    Export:
      Name: !Sub "${EnvName}-AppSecurityGroupId"
