AWSTemplateFormatVersion: '2010-09-09'
Description: >
  RDS MySQL in private subnets for 3-tier CI/CD project (using Secrets Manager)

Parameters:
  EnvName:
    Type: String
    AllowedValues:
      - DEV
      - PROD
    Description: Environment name (e.g., DEV, PROD)

  DBName:
    Type: String
    Default: appdb
    Description: The name of the database to create

Resources:
  # --------------------------------------------------------
  # Security Group for RDS
  # --------------------------------------------------------
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access within VPC
      VpcId: !ImportValue
        Fn::Sub: '${EnvName}-VpcId'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue
            Fn::Sub: '${EnvName}-AppSecurityGroupId'
      Tags:
        - Key: Name
          Value: !Sub '${EnvName}-db-sg'

  # --------------------------------------------------------
  # Subnet Group for RDS (Private Subnets)
  # --------------------------------------------------------
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets for RDS instance
      SubnetIds: !Split
        - ","
        - !ImportValue
          Fn::Sub: '${EnvName}-PrivateSubnets'
      Tags:
        - Key: Name
          Value: !Sub '${EnvName}-db-subnet-group'

  # --------------------------------------------------------
  # RDS Database Instance (using Secrets Manager for creds)
  # --------------------------------------------------------
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub '${EnvName}-mysql-db-v2'
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: "8.0.39"
      DBName: !Ref DBName
      MasterUsername: "{{resolve:secretsmanager:myapp/dbcredentials:SecretString:username}}"
      MasterUserPassword: "{{resolve:secretsmanager:myapp/dbcredentials:SecretString:password}}"
      VPCSecurityGroups:
        - !Ref DbSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: false
      DeletionProtection: false
      BackupRetentionPeriod: 1
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Sub '${EnvName}-mysql-db'

Outputs:
  DbEndpoint:
    Description: The RDS MySQL endpoint
    Value: !GetAtt MyDBInstance.Endpoint.Address
    Export:
      Name: !Sub '${EnvName}-DbEndpoint'

  DbName:
    Description: Database name
    Value: !Ref DBName
    Export:
      Name: !Sub '${EnvName}-DbName'
